version: '3.7'

services:
  backend-server:
    build: ./backend
    volumes:
      - ./backend/app.js:/home/node/app/app.js
    ports:
      - 8080:80
  frontend-server:
    build: ./frontend
    volumes:
      - ./frontend/src:/var/www/html
    ports:
      - 80:80
