version: '3.7'

services:
  backend-server:
    build: ./backend
#    volumes:
#      - ./backend:/home/node/app
    ports:
      - 8080:80
  frontend-server:
    build: ./frontend
    volumes:
      - ./frontend/src:/var/www/html
    ports:
      - 80:80
